GitHub action to update jdks.yaml
gradle/update-jdks-action pull request #3
Opened 2024-10-24 00:02 UTC by blindpirate

Fixes https://github.com/gradle/gradle-private/issues/4506

See here for the example usage: https://github.com/blindpirate/gradle/blob/master/.github/workflows/update-jdks.yml

This is the example PR created: https://github.com/blindpirate/gradle/pull/30

2024-10-24 07:35 UTC, ov7a commented on src/index.ts
> +  const response = await axios.get(apiUrl)
🤔 do we need an extra lib for that? `fetch` can do the work

2024-10-24 07:35 UTC, ov7a commented on src/index.ts
> +    return { version: latestAsset.release_name, sha256: latestAsset.binary.package.checksum }
❌ I think we should check that those values are present to avoid "undefined"

2024-10-24 07:59 UTC, cobexer requested changes

2024-10-24 07:59 UTC, cobexer commented on src/index.ts
> +import * as core from '@actions/core'
❌ Should have our usual copyright header

2024-10-24 07:59 UTC, cobexer commented on src/index.ts
> +      `Invalid data structure: expected release_name and binary.package.checksum in the response for JDK ${majorVersion}`
💅 we should log the response here to simplify debugging

2024-10-28 14:37 UTC, cobexer approved these changes
LGTM

2024-10-28 23:47 UTC, merged